# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}

# Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml .
COPY src/ ./src/

RUN pip install --no-cache-dir .

EXPOSE 8501

CMD ["streamlit", "run", "src/nim_rag/app.py"]
